### ISSUE TITLE
After Last Upate chest owner error

### ISSUE THREAD

**Issue by SiriosDev** [Edivad99/DimStorage#14]
original:
dopo l'ultimo aggiornamento non riesco più ad accedere alle mie chest, risultano intestate a "Owner: "
translated:
after the last update I can't access my chest anymore, they are registered to "Owner:"

**Comment by Edivad99** [comment]
I know, as notes of the update I wrote it.  I changed the save method to get around the name change problem.  So it's normal that you don't open the chest. Try to go back in version and move content to public frequency.  I don't know if this solves the problem.

**Comment by SiriosDev** [comment]
unfortunately no, btw I used the chest only for streams, so I was able to replace the chest, thanks anyway
