### ISSUE TITLE
Dimchest cannot be dismantled after the update, not even as admin

### ISSUE THREAD

**Issue by Lice2** [Edivad99/DimStorage#15]
**Describe the bug**

**Configuration**
Mod version: DimStorage-1.14.4-2.3.2.jar
Forge version: 1.14.4-forge-28.2.0
Minecraft version: 1.14.4
Are you playing on server?: i am server hoster ! and yes i play on my server

The Dimchest was placed before the update, and now it cannot be dismantled.

**Comment by Edivad99** [comment]
It's normal, not being the owner of DimChest, the mod won't let you destroy it. Switch to creative to solve the problem.
