### ISSUE TITLE
Support for ComputerCraft peripheral

### ISSUE THREAD

**Issue by BartAlcorn** [Edivad99/DimStorage#17]
OpenComputers is not available on Minecraft 1.14/1.15+, but versions of ComputerCraft are. (cc-tweaked-1.15.2-1.86.2 for example)

Support for ComputerCraft Peripherals, in the same manner as OpenComputer Components, would be most appreciated, and immediately usable on version 1.14+ worlds.

**Comment by Edivad99** [comment]
The problem is that CC: Tweaked doesn't have an api system, so I have no way to implement this mod on DimStorage
