### ISSUE TITLE
[1.15.2] Server crash on startup

### ISSUE THREAD

**Issue by ocram9** [Edivad99/DimStorage#24]
**Describe the bug**
As title.

**Configuration**
Mod version: 3.1.1
Forge version: 31.1.47
Minecraft version: 1.15.2
Are you playing on server?: Yes

**Additional context**
Latest log: https://gist.github.com/ocram9/cb9f43b44ea7a3de37b70617a3a88d64
Crash log: https://gist.github.com/ocram9/c1966136c3c8013f8d83aa88884fabb6

**Comment by Edivad99** [comment]
What version of TheOneProbe do you have installed?

**Comment by ocram9** [comment]
None, I don't use TheOneProbe. I do use Hwyla version 1.10.8-B72_1.15.2

**Comment by Edivad99** [comment]
Your error is very strange, there is no problem on my server

**Comment by ocram9** [comment]
Then it might be a mod compatibility issue. Downgrading back to 3.1.0 fixed the issue

**Comment by Edivad99** [comment]
Try to delete the mod, but not the DimStorage folder found in the saves. Enter the world, confirm that you want to remove all things related to DimStrorage. Then try to put the updated mod back. You should not lose the contents of the chest

**Comment by ocram9** [comment]
I will do in a sec but I just tested the newest version in a completely new server and it still crashed:

Latest: https://gist.github.com/ocram9/56f17c6531586ca5f618880880801412
Crash: https://gist.github.com/ocram9/8e0f482ff8f36b24a795895972001638

**Comment by ocram9** [comment]
Removed dimstorage, started the server and put the new version back. It crashed again as soon as I put the new version in.

**Comment by Edivad99** [comment]
For now it seems that with TheOneProbe there is no problem, it crashes when there is no TOP.

**Comment by Edivad99** [comment]
Ok I confirm it was a problem with the TOP, soon an update will come out to fix the problem

**Comment by ocram9** [comment]
Awesome, thank you!

**Comment by Edivad99** [comment]
Ok the updates are under review, as soon as they are ready could you tell me if the problem has disappeared to you too?

**Comment by ocram9** [comment]
Server started without any problems, it seems to have been fixed

**Comment by Edivad99** [comment]
Perfect💪💪
