### ISSUE TITLE
Dimensional Chest destroyed when breaking with pickaxe

### ISSUE THREAD

**Issue by bessiq** [Edivad99/DimStorage#26]
**Describe the bug**
Dimensional Chests are destroyed when breaking them. This did not happen on previous mod versions. I am using the same pickaxes, and one even has Silk Touch. The chest is destroyed regardless.

**Configuration**
Mod version: DimStorage-1.15.2-3.1.4
Forge version: forge-31.2.0
Minecraft version: 1.15.2
Are you playing on server?: Yes, running modpack ATM5 v1.25

**To Reproduce**
1. Place Dimensional Chest
2. Break Dimensional Chest using appropriate tool (pickaxe)

**Expected behavior**
Upon breaking, the chest should drop to the ground to be picked up.

**Comment by Edivad99** [comment]
Thanks, an update will be released within 24 hours to fix the bug
