### ISSUE TITLE
[1.15.2] /dimtablet Commands Server vs. Client

### ISSUE THREAD

**Issue by GatekeeperTDS** [Edivad99/DimStorage#32]
I noticed in the latest version that a dimstorage-server.toml file was created in the serverconfig folder, and this is where server settings are now instead of the common file, but even before this change there is a strange behavior with the /dimtablet commands where it affects the entire server's config, even before the recent change.

When an item is added to the auto-picking list using **dimtablet /add**, the configuration is changed for the entire server and all players. This part of the configuration should be moved to a **dimstorage-client.toml** file and only affect the current player's client, not the entire server.

Thank you.

**Comment by GatekeeperTDS** [comment]
This is still present in the 1.16 builds.

**Comment by Edivad99** [comment]
From what I know the client file is to be used for things like rendering. The process of taking files from the player's inventory and placing them into the dimchest must take place on the server. If you want to try to see change the code and if it works open a pull request.

**Comment by GatekeeperTDS** [comment]
I'm afraid Java programming is a bit outside my skill scope. :)

I see what you mean, though, it definitely needs to be stored on the server for it to work properly. The issue is that the list isn't unique per user. So say I whitelist minecraft:dirt for pickup but other people on the server don't want that, there's no choice. Could the list maybe be stored in the user's data or in another config file by user?
