### ISSUE TITLE
[1.16.1] Tanks/Chests get 'locked' after server restart.

### ISSUE THREAD

**Issue by WhitePhant0m** [Edivad99/DimStorage#34]
**Describe the bug**
Whenever a server restarts, the tanks/chests get 'locked'. All pipes and importers and such can't connect to them unless you either break and place them down again or lock and unlock them.

**Configuration**
Mod version: DimStorage-1.16.1-4.0.2
Forge version: 32.0.108
Minecraft version: 1.16.1
Are you playing on server?: Yes

**To Reproduce**
1. Place down a dim tank/chest
2. Connect a pipe to it or an importer/exporter
3. Restart server
4. Notice that the pipe is not connected nor can you import/export items from/to it

**Expected behavior**
For the chests/tanks to not 'lock' after a restart

**Screenshots**
![image](https://user-images.githubusercontent.com/33400200/91100462-ef5e9b80-e66d-11ea-849a-332397164278.png)

**Comment by Edivad99** [comment]
Ok, thanks for the report, I already have a fix ready but it will be added in version 1.16.2 as 1.16.1 will no longer be updated

**Comment by DoomSquirter** [comment]
is there any way to get this update to 1.16.1 as well?   

I see you state that it's not going to be updated anymore, but ATM6 is still on 1.16.1 for release and latest beta is on 1.16.2 but doesn't have a bunch of mods still.  Not sure when things will be updated.  would be really awesome to have this fix in a 1.16.1 version as well.

**Comment by Edivad99** [comment]
@DoomSquirter The update for 1.16.3 and 1.16.1 comes out on Wednesday. I'll fix all the bugs

**Comment by Edivad99** [comment]
https://www.curseforge.com/minecraft/mc-mods/dimstorage/files/3057613
