### ISSUE TITLE
DimChest locks after going through nether portal

### ISSUE THREAD

**Issue by karate867** [Edivad99/DimStorage#35]
I set up a guardian farm using a dimchest to collect with the hope of being able to then have a linked chest deposit into my storage system.  Unfortunately, after setting up the chest, when I return the overworld I see no items flowing in, even while I'm at my farm and see guardians making their way through the system.  Is this intended, or is there some way to override this and prevent the locking from occurring?  If not, is there a plan to address this moving forward?

**Comment by Edivad99** [comment]
I did not understand what you mean... The dimchest set on collect does not take items from entities but from inventories such as chest, barrels, furnaces...

**Comment by karate867** [comment]
I apologize, to be more clear I have a hopper that runs into the dimchest, however it stops receiving items from the hopper when I go through a nether portal.  It's currently set to idle, not collecting.

**Comment by Edivad99** [comment]
You probably don't have a chunk loader that loads that zone
