### ISSUE TITLE
Having to reset the tanks an chests everytime u log in

### ISSUE THREAD

**Issue by Raiderax** [Edivad99/DimStorage#36]
Everytime i log in i have to go into the nether an reset the tank to get it to accept fluid an the same thing happens with the chests dunno if this is the way it was coded or if its a bug

Version 1.16.1 -4.0.2
Forge version 32.0.1.08
 Minecraft version 1.16.1
Single player

**Configuration**
Mod version:
Forge version:
Minecraft version:
Are you playing on server?:

Was expecting to not have to reset the auto eject idle feature to get the tanks/chests to accept items again does it everytime i relog or log in

**Comment by Edivad99** [comment]
This bug has already been fixed #34
