### ISSUE TITLE
Crash when trying to connect mekanism pipes in dim tank

### ISSUE THREAD

**Issue by sidyamamoto** [Edivad99/DimStorage#38]
**Describe the bug**
Crash when trying to connect mekanism pipes in dim tank.

**Configuration**
Mod version: 4.0.3
Forge version: 32.0.108
Minecraft version: 1.16.1
Are you playing on server?: No

**To Reproduce**
1. Create a Dim Tank
2. Try to connect a Mekanism Pipe into it. 

If I revert to the previous version of dimstorage (4.0.2) the pipe doesn't connect, but the game opens at least.

**Comment by Edivad99** [comment]
Can you give me the error log?

**Comment by Edivad99** [comment]
Anyway for version 1.16.1 no new versions will be released

**Comment by sidyamamoto** [comment]
Well that's unfortunate. Let's hope that mekanism and other popular tech mods releases new versions soon then. Thanks.

**Comment by sidyamamoto** [comment]
About the error, it creates a ticking block entity error in the pipe that's trying to connect to the dim tank.
[crash-2020-10-02_19.21.10-server.txt](https://github.com/Edivad99/DimStorage/files/5321694/crash-2020-10-02_19.21.10-server.txt)

**Comment by Edivad99** [comment]
Yes it is strange, I have already fixed a couple of things on DimStorage for 1.16.3 that could be related to this problem. As you say we are waiting for Mekanism to publish a version for 1.16.3 where I think I understand they have optimized a couple of things themselves. Thanks for the log, I will not investigate in detail. If that happens even for 1.16.3 I will definitely take action.
