### ISSUE TITLE
Player keep being disconnected, console spam and eventually server crash when Dim Chest is set to private

### ISSUE THREAD

**Issue by lllMohandarlll** [Edivad99/DimStorage#39]
**Describe the bug**
A player player crafted some dimensional chest, put one down, set it private and has been disconneted from server, being then disconnected every time he tryied to log back in, until I destroyed the dimensional chest for him on op level 4.
We tested that again at that point to be sure, with the same result

**Configuration**
Mod version: DimStorage-1.12.2-1.3.0
Forge version:  1.12.2 - 14.23.5.2854
Minecraft version: 1.12.2
Are you playing on server?: yes

**To Reproduce**
Steps to reproduce the behavior:  the same of the description I guess

**Expected behavior**
the player not getting dc? lol

**Additional context**
the relevant part in the pastebin is the
at net.minecraft.nbt.NBTTagCompound.writeEntry(NBTTagCompound.java:475) ~[fy.class:?]
console spam at the bottom, I guess

[https://pastebin.com/](https://pastebin.com/)

Well... I just hope 1.12.2 is still supported, we've switched to Ender Storage in the meanwhile

**Comment by Edivad99** [comment]
The version for 1.12.2 is no longer supported, I do not recommend using it because it is probably full of bugs. 
Stable versions of dimstorage are from 1.14.4 onwards.

**Comment by lllMohandarlll** [comment]
You can reccomend me to upgrade as much as you like but since mods are almost never being used alone but in modpacks and since the whole modpack is set on 1.12.2 I'd rather change Dimensional Chest with Ender Storage.
Thanks for the support anyway.
