### ISSUE TITLE
[1.12.2] OpenComputers is marked as an optional dependency

### ISSUE THREAD

**Issue by 04Slash** [Edivad99/DimStorage#40]
**Describe the bug**
[On Curseforge](https://www.curseforge.com/minecraft/mc-mods/dimstorage/files/2851358), OpenComputers is listed as an optional dependency. Without OC, the game will crash because it can't find an OC class.

**Configuration**
Mod version: DimStorage-1.12.2-1.3.0
Forge version: N/A
Minecraft version: 1.12.2
Are you playing on server?: N/A

**To Reproduce**
1. Put DimStorage in mods folder
2. Start game
3. Crash -> https://pastebin.com/LdtgcjQC

**Expected behavior**
OC needs to be marked as a required dependency so that when this mod is downloaded with a launcher it automatically downloads OC as well, preventing a crash.

**Screenshots**

**Additional context**

**Comment by Edivad99** [comment]
1.12.2 is no longer supported

**Comment by 04Slash** [comment]
I understand if you don't wish to support 1.12.2 anymore but this is a fix that should take no more than a minute. The only thing that needs to be done is marking OC as a required dependency on curseforge. No code fixes or anything else.
