### ISSUE TITLE
Interaction with refined storage causes voided drives!!! :( 

### ISSUE THREAD

**Issue by BrettMoan** [Edivad99/DimStorage#41]
**Describe the bug**
this is an "unexpected interaction" bug between this mod and popular mods https://github.com/refinedmods/refinedstorage.

I'm also using https://github.com/Edivad99/ExtraStorage and https://github.com/MelanX/ExtraDisks but i believe this can be reproduced without those mods. that said, there's a possibility the interactions comes from either the Importer from @extrastorage, or the drive from @extradisks, so i'm noting it for completeness. 

to produce the bug, one would basically make a "compact" ME setup with a dimensional chest, being within the 3x3 of the refined storage "disk drive"  and an importer pointing from the Dimensional chest to the ME system, results in drive being pulled form the dimensional storage without a block update on the "disk drive" and the drive(s) that was/were placed in the into the ME systems "storage" even though that drive is no longer in the "disk drive". what happens is it causes the drive to be stored "within itself".  

(I used @ExtraStorage "advanced importer" but I'm guessing a @refinedstorage importer would do the same) 

if noticed the drive can be retrieved from a "crafting grid" but only if done quickly. if not noticed, then the system will void the drive. which could lead to loss of millions of items. like in in my case .

I'm going to open a related issue on the other mods involved in the interaction, hopefully you guys can figure out what the best fix is, but current behavior is certainly a harrowing experience as you could be like me, where i just lost 100k and several weeks of progression, on a public server where I'm not OP and can't give myself back the important items. :( 

ultimately I it would be a good idea to black list the "disk drive" block on the collecting if possible, as I very very very much doubt this is going to be the intended functionality for the **majority** of people. 

alternatively i think the dimensional chest would need to preform a "block update" when it pulls the items, as the disk drive block doesn't realize the drive has been pulled from it. 

**Configuration**
Mod version: 4.4.0
Forge version: 36.1.2
Minecraft version: 1.16
Are you playing on server?: yes.  public server for TNP Limitless 3 mod pack

**To Reproduce**
here are the Steps to reproduce the behavior and what i see as the "bugs" in the interaction:

1. set up a simple refined storage ME system with an advanced importer pointing to the dimensional chest and a "disk drive" from refined storage within the 3x3 of the  dimensional chest. 
2. insert a single drive into the "disk drive" 
3. click the "collecting" button on the dimensional chest within a 3x3 of the "disk drive" of the 
4. watch the drive get pulled from the "disk drive" from refined storage.  (this is not expected behavior, the "disk drive" could/should be black listed on the collecting config)
but still get imported into the the crafting storage.
5. watch the advanced importer still pull the drive out of the dimensional chest  and push it into the ME. (this is not expected behavior, the "disk drive" no longer has any disks, how is the importer still importing the items?)
6. after closing the dimensional chest UI, notice the block of the "disk drive" hasn't been updated, and it still "visually" looks like the disk is there. (likely bug caused by dimensional chest not updating the "disk drive" block when it does the collecting)
7. right click the "disk drive" block, to confirm the drive isn't there. (even though the block "visually" has it in the world, just not in the UI.
8. click the crafting grid, notice that the drive is there and at this point so are all the items. and if you hover over the drive, it, it will  have the count of all items in it, but now +1 as its "stored within itself" (likely bug caused by dimensional chest not updating the "disk drive" block when it does the collecting)
9. if smart, pull the drive out of the ME, and put it back in the "disk drive" which will force a block update on the disk drive. 

**Expected behavior**
the dimensional chest shouldn't be "collecting" the drive from the disk drive. I very much doubt any player will ever have this as "expected" behavior, and so it would  be good to black list that block. may also want to look into what other blocks it "collects" from that maybe could be added to a black list. if you do decide to keep updating form that block, then the block needs to be updated, so that it can tell the rest of the ME, that it no longer has storage. so it can turn the importer OFF.

**Screenshots**
![image](https://user-images.githubusercontent.com/6159590/112249309-c0fd6a80-8c14-11eb-95a9-268c19b9545e.png)
here you can see a "compact" setup of an ME system, where the Dimensional Chest is being used as a "send it to the ME system"  such as for long exploring adventure.

here you can see the drive with it stored within itself
![image](https://user-images.githubusercontent.com/6159590/112251014-a8db1a80-8c17-11eb-81bf-f67ebbc7dfd6.png)

**Additional context**
no problem occurs unless the "collecting" button is pressed. I assume there also wouldn't be a problem if the disk drive was outside the 3x3 radius, but since this just voided all my items including my cable... i don't really have the time to test before opening the issue.

**Comment by Edivad99** [comment]
How does DimChest take the disk that is inside the disk drive? The control takes place in the faces of the block

**Comment by Edivad99** [comment]
With the latest version of DimStorage-1.16.5-4.4.1, this problem is solved, as the "Collect" button no longer exists
