### ISSUE TITLE
Add new configuration

### ISSUE THREAD

**Issue by Ki-Tan2934** [Edivad99/DimStorage#42]
Allow collection to be disabled from dim storage to stop duping and griefing.
Dim storage will not be added to the next ATM pack if not fixed and may be removed from current active packs

**Comment by Edivad99** [comment]
This feature will be removed in future versions because it is creating a lot of problems. Over the weekend I should release the latest update for 1.16.5

**Comment by Edivad99** [comment]
Ok, updated the mod!😅

**Comment by Ki-Tan2934** [comment]
Thanks for patching so fast
