### ISSUE TITLE
Can I turn off update detection？

### ISSUE THREAD

**Issue by xuwuwudi** [Edivad99/DimStorage#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I enter the game, the update prompt and changelog are displayed in the chat box, but there is no new version, and my game is stuck here. It's not that the window doesn't respond. I can't do anything just in that screen,that I had to force the game to restart...
But it's strange that this won't happen the second time I enter the game........
![image](https://user-images.githubusercontent.com/84704462/171171167-8f323884-68fe-4aeb-9430-2eb13bf7f258.png)

### How can I reproduce this bug or crash?

Open the game and enter the world

### Configuration

```markdown
- Mod version:DimStorage-1.18.2-6.1.0
- Forge version:40.1.25
- Minecraft version:1.18.2
```

**Comment by Edivad99** [comment]
This is strange, in the meantime you can disable forge version checking in `fml.toml` and it will be fine
