### ISSUE TITLE
dimstorage-server.toml is not correct

### ISSUE THREAD

**Issue by towzzer** [Edivad99/DimStorage#50]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

currently running an ATM 8 server and am constantly spammed with this in the console. How can I configure the file to repair it?

[Thread-0/WARN] [net.minecraftforge.fml.config.ConfigFileTypeHandler/CONFIG]: Configuration file C:\Users\black\OneDrive\Desktop\The one true server\.\Boi\serverconfig\dimstorage-server.toml is not correct. Correcting

### How can I reproduce this bug or crash?

happens every time I launch my server

### Configuration

```markdown
- Mod version:7.2.0
- Forge version:43.1.25
- Minecraft version:1.19.2
```

**Comment by LucasMcToucas** [comment]
i am still getting this with version 1.0.10, can someone please help

**Comment by DJMo13** [comment]
well, still exists with 1.0.19 :-(
already deleted the configs and installed everything again

**Comment by LucasMcToucas** [comment]
It was because it was in a one drive location
