### ISSUE TITLE
Button missing on Dimensional Chest?

### ISSUE THREAD

**Issue by Arcwin** [Edivad99/DimStorage#52]
Videos and pictures for the chest show a button in the GUI below 'Locked?' for controlling input/output options for the chest as shown in this pic from 9minecraft.net

https://www.9minecraft.net/wp-content/uploads/2020/04/DimStorage-mod-for-minecraft-03.jpg

I am in All The Modes 8, which is 1.19.2 and the button isn't there on the chest I made, oddly.  Pic here:

https://www.flickr.com/photos/197625247@N03/52668255667/

Wondering if I need a new version?  The mod is using DimStorage-1.19.2-7.2.0.jar which Curseforge shows as the latest.

**Comment by Edivad99** [comment]
https://github.com/Edivad99/DimStorage/issues/51
