### ISSUE TITLE
No longer able to access a locked chest after player name change

### ISSUE THREAD

**Issue by trevorjd** [Edivad99/DimStorage#65]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A player on my server changed their in-game name and they no longer have access to their locked chests.  They are also not able to break/pick up the chest block.  As an op, neither can I however I can destroy the chest in creative mode.

We had the player replace the chest and it links back into the same player/frequency network, which is great as all we've needed to do is replace the chests.

My guess is you're using the playerID for the network, but the playerName for access control.  Is it possible to use the playerID for access control too and do a lookup of the playerName for display purposes?

Thanks!

### How can I reproduce this bug or crash?

Place a dimstorage chest
Lock it to a player
Change player name
Try to open dimstorage chest

### Configuration

```markdown
- Mod version:  DimStorage-1.21-9.0.2
- Forge version:  neoforge-21.1.83
- Minecraft version:  1.21.1
```

**Comment by trevorjd** [comment]
Thanks!

**Comment by jheyemm** [comment]
Sorry to add on this thread but I just got the same problem. Would you care to share the solution to this?

**Comment by trevorjd** [comment]
> Sorry to add on this thread but I just got the same problem. Would you care to share the solution to this?

@jheyemm Edivad99 fixed it in code on Dec 22.  Unfortunately they haven't published a new version of the mod yet but when they do, players should still be able to access a chest after changing their in-game name.

**Comment by Edivad99** [comment]
Sorry guys, I forgot to release the fix.
Even though I'm late, I've released a new version.
